### ISSUE TITLE
Disabling ImageTriggerChange on DC object creation does not trigger deployment

### ISSUE THREAD

**Issue by Victoremepunto** [bsquizz/ocdeployer#48]
If you try to deploy a new service, and the template includes the DC's ImageTrigger as disabled, that is :

```
  spec:
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: false    # <= 
```

After running `oc deployer deploy` the deployment won't run and the command will timeout waiting for the service to be ready.
